Update patch set 3
Patch Set 3:

> By the way, I highly doubt that you only need the "overload
 > makeSubscriptionInfo" with tissot's 8.1 blobs. I tried those and
 > was getting this.
 > 
 > >  04-27 23:14:24.953  1860  1860 I zygote64: Rejecting re-init on
 > previously-failed class java.lang.Class<com.qualcomm.qti.internal.telephony.QtiRIL>:
 > java.lang.IncompatibleClassChangeError: Superclass
 > com.android.internal.telephony.RIL of com.qualcomm.qti.internal.telephony.QtiRIL
 > is declared final (declaration of 'com.qualcomm.qti.internal.telephony.QtiRIL'
 > appears in /system/framework/qti-telephony-common.jar)
 > 
 > Solved with this patch, but unfortunately SIM cards are still not
 > detected.

this crash is there from o blobs itself tho it does not harm any functioning (or i never noticed it)and for the network part i already stated modem update is required for new blobs

Patch-set: 3
Reviewer: Abhishek <13559@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>