Update patch set 1
Patch Set 1: Code-Review+1

These commit's change a method used in the prebuilt ims.apk that shamu uses, causing the following error.

03-25 00:42:44.470: E/ImsServiceSub(1622): java.lang.NoSuchMethodError: No interface method registrationDisconnected()V in class Lcom/android/ims/internal/IImsRegistrationListener; or its super classes (declaration of 'com.android.ims.internal.IImsRegistrationListener' appears in /system/framework/framework.jar:classes2.dex) createRegCallBackThread()

Patch-set: 1
Reviewer: David Hacker <8640@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Code-Review=+1