Update patch set 1
Patch Set 1:

(1 comment)

This breaks the build on cm-12.1 with:

frameworks/opt/telephony/src/java/com/android/internal/telephony/dataconnection/DcTracker.java:905: error: boolean cannot be dereferenced
                reason += " - Attached= " + attachedState.get();
                                                         ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

attachedState is a boolean:

boolean attachedState = mAttached.get();

Patch-set: 1
Reviewer: Alexandre Dumont <1829@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0