Prevent array out of bounds exception in handleMessage
In EVENT_ALL_DATA_DISCONNECTED the phoneId turns out to be -1 in
builds for dual sim devices (e.g. Titan) which causes fatal exception.
java.lang.ArrayIndexOutOfBoundsException: length=2; index=-1
at com.android.internal.telephony.dataconnection.DctController.handleMessage(DctController.java:368)

This occurs after the following CM commit being merged:
http://review.cyanogenmod.org/#/c/95779/

Change-Id: I7d05c03068ddd574bea894bbc5971ed6944753ff