Update patch set 2
Patch Set 2: Code-Review-1

Not sure if I'm missing a dependency:

frameworks/opt/telephony/src/java/com/android/internal/telephony/uicc/UiccCard.java:199: error: cannot find symbol
                    && mCi.needsOldRilFeature("simactivation")) {
                          ^
  symbol:   method needsOldRilFeature(String)
  location: variable mCi of type CommandsInterface

Patch-set: 2